#!/bin/bash

# knockpy v5.0.0 docker
# url: https://hub.docker.com/r/nocommentlab/knock
# contributor: Antonio Blescia

# usage: ./kdocker domain.com <arg1> <arg2> <argn>

if [ ! $(which docker) ]; then
	echo "install docker"
	exit
fi

if [[ ! -f "config.json" ]]; then
	wget -q https://raw.githubusercontent.com/guelfoweb/knock/master/knockpy/config.json
fi

docker run --volume :/knock/knockpy/config.json --rm nocommentlab/knock:5.0.0 $@